[package]
name = "dhbw-typst-template"
version = "0.1.0"
entrypoint = "src/dhbw-typst-template.typ"
authors = ["cocoveal <https://github.com/cocoveal>", "nikmtl <https://github.com/nikmtl/dhbw-typst-template>"]
license = "MIT"
description = "Template for TX000 papers at DHBW Mannheim"
keywords = ["template", "dhbw", "thesis"]
categories = ["paper", "thesis", "report"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
